export const GET_LIST_POST = "GET_LIST_POST";
export const GET_LIST_POST_SUCCESS = "GET_LIST_POST_SUCCESS";

export const GET_SEARCH_LIST_POST = "GET_SEARCH_LIST_POST";
export const GET_SEARCH_LIST_POST_SUCCESS = "GET_SEARCH_LIST_POST_SUCCESS";
export const GET_POST_BY_ID = "GET_POST_BY_ID";
export const GET_POST_BY_ID_SUCCESS = "GET_POST_BY_ID_SUCCESS";

export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";

export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
