export const GET_LIST_POST = "GET_LIST_POST";
export const GET_LIST_POST_SUCCESS = "GET_LIST_POST_SUCCESS";

export const GET_SEARCH_LIST_POST = "GET_SEARCH_LIST_POST";
export const GET_SEARCH_LIST_POST_SUCCESS = "GET_SEARCH_LIST_POST_SUCCESS";
